package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.AwsConnection
import jetbrains.buildServer.configs.kotlin.projectFeatures.awsConnection
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        val feature1 = find<AwsConnection> {
            awsConnection {
                id = "AiAgentTesting_BuildfarmAws"
                name = "Buildfarm AWS"
                regionName = "eu-west-1"
                credentialsType = static {
                    accessKeyId = "AKIARLPX3CIT7X546WXD"
                    secretAccessKey = "credentialsJSON:10a5256d-4fb6-47d6-9900-4092445cc797"
                }
                allowInBuilds = false
                stsEndpoint = "https://sts.eu-west-1.amazonaws.com"
            }
        }
        feature1.apply {
        }
    }
}
